name: CI Pipeline

on:
  push:
    branches: [ main, feat/* ]
  pull_request:
    branches: [ main ]

jobs:
  backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: dayflow-hrms/backend

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: dayflow-hrms/backend/package-lock.json

      - name: Install Dependencies
        run: npm ci

      - name: Type Check & Build
        run: npm run build

      - name: Run Unit/Security Tests
        run: |
          npx ts-node tests/auth.test.ts
          npx ts-node tests/signup.test.ts
          npx ts-node tests/leave.overlap.test.ts
          npx ts-node tests/authz-idor.test.ts

  frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: dayflow-hrms/frontend

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: dayflow-hrms/frontend/package-lock.json

      - name: Install Dependencies
        run: npm ci

      - name: Type Check & Build
        run: npm run build
